In [1]:
import numpy as np

# Create a 1D array
arr1d = np.array([1, 2, 3, 4, 5])

# Create a 2D array
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(arr1d)
print(arr2d)


[1 2 3 4 5]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [2]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

# Element-wise addition
result = arr + 10

print(result)  # Output: [11 12 13 14 15]


[11 12 13 14 15]


In [3]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

# Square root of each element
result = np.sqrt(arr)

print(result)  # Output: [1.         1.41421356 1.73205081 2.         2.23606798]


[1.         1.41421356 1.73205081 2.         2.23606798]


In [4]:
import numpy as np

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# Matrix multiplication
result = np.dot(A, B)

print(result)  # Output: [[19 22] [43 50]]


[[19 22]
 [43 50]]


In [5]:
import numpy as np

# Generate an array of 5 random integers between 0 and 10
random_arr = np.random.randint(0, 10, size=5)

print(random_arr)  # Output: [3 6 2 8 1]


[3 8 4 7 1]


In [6]:
import pandas as pd

# Create a DataFrame from a dictionary
data = {'Name': ['Alice', 'Bob', 'Charlie'], 'Age': [25, 30, 35]}
df = pd.DataFrame(data)

print(df)


      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   35


In [7]:
import pandas as pd

# Select rows where Age is greater than 25
result = df[df['Age'] > 25]

print(result)


      Name  Age
1      Bob   30
2  Charlie   35


In [8]:
import pandas as pd

# Drop rows with missing values
df_clean = df.dropna()

# Fill missing values with a specific value
df_filled = df.fillna(0)

print(df_clean)
print(df_filled)


      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   35
      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   35


In [9]:
import pandas as pd

# Create a DataFrame with a DatetimeIndex
dates = pd.date_range(start='2022-01-01', end='2022-01-05')
data = {'Value': [10, 20, 30, 40, 50]}
ts_df = pd.DataFrame(data, index=dates)

print(ts_df)


            Value
2022-01-01     10
2022-01-02     20
2022-01-03     30
2022-01-04     40
2022-01-05     50


In [10]:
import pandas as pd
import matplotlib.pyplot as plt

# Plot a DataFrame
df.plot(kind='line', x='Date', y='Value')
plt.show()


KeyError: 'Date'