In [1]:
import tensorflow as tf

In [2]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()

x_train, x_test = x_train / 255.0, x_test / 255.0

11493376/11490434 [==============================] - 0s 0us/step


In [3]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

In [4]:
predictions = model(x_train[:1]).numpy()
predictions

array([[-0.2559589 , -0.4459507 , -0.3821684 ,  0.7185288 , -0.04217005,
         0.29842895,  0.6545241 , -1.1204977 , -0.16933328,  1.2719198 ]],
      dtype=float32)

In [5]:
tf.nn.softmax(predictions).numpy()

array([[0.05902111, 0.04880846, 0.05202299, 0.15639469, 0.07308945,
        0.10274838, 0.14669831, 0.0248624 , 0.06436183, 0.27199236]],
      dtype=float32)

In [6]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [7]:
loss_fn(y_train[:1], predictions).numpy()

2.2754722

In [8]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [9]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 12s 6ms/step - loss: 0.4822 - accuracy: 0.8577
Epoch 2/5
1875/1875 [==============================] - 11s 6ms/step - loss: 0.1542 - accuracy: 0.9546
Epoch 3/5
1875/1875 [==============================] - 11s 6ms/step - loss: 0.1107 - accuracy: 0.9662
Epoch 4/5
1875/1875 [==============================] - 11s 6ms/step - loss: 0.0881 - accuracy: 0.9724
Epoch 5/5
1875/1875 [==============================] - 11s 6ms/step - loss: 0.0713 - accuracy: 0.9773


In [10]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 1s - loss: 0.0807 - accuracy: 0.9749


[0.08069450408220291, 0.9749000072479248]

In [11]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [12]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[1.0686994e-08, 2.5568192e-09, 5.9793965e-06, 1.1462018e-04,
        1.6011316e-12, 3.8401023e-08, 7.4360749e-13, 9.9985337e-01,
        2.9111487e-07, 2.5741123e-05],
       [4.0497207e-07, 2.0301585e-04, 9.9823761e-01, 1.1738221e-03,
        5.3665292e-16, 1.6647362e-04, 1.2570846e-06, 1.8770476e-11,
        2.1736533e-04, 1.4070288e-12],
       [2.2474468e-07, 9.9963689e-01, 2.3402292e-05, 1.8398561e-05,
        2.8121340e-05, 2.8804682e-06, 1.4221564e-05, 2.2141858e-04,
        5.3790194e-05, 6.3884261e-07],
       [9.9944848e-01, 5.9994613e-07, 1.5521402e-04, 4.1341482e-06,
        9.6505808e-09, 4.1292878e-05, 9.8183678e-05, 2.0107689e-04,
        6.1885174e-07, 5.0359482e-05],
       [6.7330939e-06, 1.5601702e-07, 1.3846982e-06, 8.9785232e-08,
        9.8852879e-01, 6.1181430e-07, 1.4377130e-05, 2.1326191e-04,
        2.9635953e-07, 1.1234218e-02]], dtype=float32)>